CREATE OR REPLACE PACKAGE CADPD_OWN.PG_FRONT_END_SYSTEM 
AS
    PROCEDURE SP_LISTAR_FES_CFG_COMUNICACAO_FUNCAO (P_RETORNO OUT SYS_REFCURSOR);

	PROCEDURE SP_MANTER_COMUNICA_CONCESSIONARIA (
		P_ID                IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.ID%TYPE,
		P_CD_CONCESSIONARIA IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_CONCESSIONARIA%TYPE,
		P_DS_CONCESSIONARIA IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_CONCESSIONARIA%TYPE,
		P_CD_REGIONAL       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_REGIONAL%TYPE,
		P_DS_REGIONAL       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_REGIONAL%TYPE,
		P_CD_MONTADORA      IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_MONTADORA%TYPE,
		P_DS_MONTADORA      IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_MONTADORA%TYPE,
		P_CD_FUNCAO         IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_FUNCAO%TYPE,
		P_DS_NOME           IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_NOME%TYPE,
		P_NM_TELEFONE       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.NM_TELEFONE%TYPE,
		P_DS_EMAIL          IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_EMAIL%TYPE,
		P_DS_USUARIO        IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_USUARIO%TYPE,
		P_FL_EMAIL_BANCO    IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_EMAIL_BANCO%TYPE,
		P_FL_EMAIL_NF       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_EMAIL_NF%TYPE,
		P_FL_PESQUISA       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_PESQUISA%TYPE,
		P_FL_NEGOCIACAO     IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_NEGOCIACAO%TYPE
	);

	PROCEDURE SP_EXCLUIR_COMUNICA_CONCESSIONARIA (
		P_ID IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.ID%TYPE
	);

	PROCEDURE SP_LISTAR_COMUNICA_CONCESSIONARIA (
		P_CD_CONCESSIONARIA		IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_CONCESSIONARIA%TYPE,
		P_DATA_INICIO         	IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DT_CADASTRO%TYPE,
		P_DATA_FIM            	IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DT_CADASTRO%TYPE,
		P_RETORNO 				OUT SYS_REFCURSOR
	);
	
	PROCEDURE SP_MANTER_AVALIACAO_CORRESPONDENTE_PAIS (
        P_ID                   IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.ID%TYPE,
        P_CD_USUARIO           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_USUARIO%TYPE,
        P_DS_USUARIO           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_USUARIO%TYPE,
        P_CD_CONCESSIONARIA    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_CONCESSIONARIA%TYPE,
        P_DS_CONCESSIONARIA    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_CONCESSIONARIA%TYPE,
        P_CD_REGIONAL          IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_REGIONAL%TYPE,
        P_DS_REGIONAL          IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_REGIONAL%TYPE,
        P_CD_MONTADORA         IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_MONTADORA%TYPE,
        P_DS_MONTADORA         IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_MONTADORA%TYPE,
        P_NM_NOME              IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.NM_NOME%TYPE,
        P_NR_CPF               IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.NR_CPF%TYPE,
        P_DS_EMAIL             IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_EMAIL%TYPE,
        P_NR_CERTIFICADO       IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.NR_CERTIFICADO%TYPE,
        P_DT_EMISSAO           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_EMISSAO%TYPE,
        P_DT_VENCIMENTO        IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_VENCIMENTO%TYPE,
        P_FL_CRACHA_VISIVEL    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CRACHA_VISIVEL%TYPE,
        P_FL_CREDITO_LOGISTA   IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CREDITO_LOGISTA%TYPE,
        P_FL_CREDITO_SITE      IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CREDITO_SITE%TYPE,
        P_FL_CORRESPONDENTE    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CORRESPONDENTE%TYPE,
        P_FL_COBRANCA_CET      IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_COBRANCA_CET%TYPE
    );

    PROCEDURE SP_EXCLUIR_AVALIACAO_CORRESPONDENTE (
        P_ID IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.ID%TYPE
    );

	PROCEDURE SP_LISTAR_AVALIACAO_CORRESPONDENTE (
        P_CD_CONCESSIONARIA  IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_CONCESSIONARIA%TYPE,
        P_DATA_INICIO        IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_CADASTRO%TYPE,
        P_DATA_FIM          IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_CADASTRO%TYPE,
        P_RETORNO           OUT SYS_REFCURSOR
    );

   PROCEDURE SP_MANTER_PILOTO (
		P_ID             IN CADPD_OWN.FES_PILOTO.ID%TYPE, 
		P_CD_IDDESCRICAO IN CADPD_OWN.FES_PILOTO.CD_IDDESCRICAO%TYPE,
		P_CD_DN          IN CADPD_OWN.FES_PILOTO.CD_DN%TYPE,
		P_CD_EMPRESA     IN CADPD_OWN.FES_PILOTO.CD_EMPRESA%TYPE,
		P_DT_INICIO      IN CADPD_OWN.FES_PILOTO.DT_INICIO%TYPE,
		P_DT_FIM         IN CADPD_OWN.FES_PILOTO.DT_FIM%TYPE,
		P_RETORNO        OUT NUMBER);

	PROCEDURE SP_MANTER_PILOTO_DESCRICAO (
		P_ID             IN CADPD_OWN.FES_DESC_PILOTO.ID%TYPE, 
		P_NM_NOME        IN CADPD_OWN.FES_DESC_PILOTO.NM_NOME%TYPE,
		P_DS_DESCRICAO   IN CADPD_OWN.FES_DESC_PILOTO.DS_DESCRICAO%TYPE,
		P_FL_ATIVO       IN CADPD_OWN.FES_DESC_PILOTO.FL_ATIVO%TYPE,
		P_RETORNO        OUT NUMBER);
		
	PROCEDURE SP_LISTAR_PILOTOS (
	  P_CD_IDDESCRICAO IN CADPD_OWN.FES_PILOTO.CD_IDDESCRICAO%TYPE,
	  P_RETORNO				OUT SYS_REFCURSOR);
	  
    PROCEDURE SP_LISTAR_PILOTOS_DESCRICAO (
		  P_ID   IN CADPD_OWN.FES_DESC_PILOTO.ID%TYPE,
		  P_RETORNO				OUT SYS_REFCURSOR);
	  
	PROCEDURE SP_LISTAR_PILOTOS_POR_DN (
	  P_CD_DN          IN CADPD_OWN.FES_PILOTO.CD_DN%TYPE,
	  P_RETORNO				OUT SYS_REFCURSOR);
	  
	PROCEDURE SP_EXPURGO_PILOTO (
		P_CD_IDDESCRICAO    IN  CADPD_OWN.FES_PILOTO.CD_IDDESCRICAO%TYPE
	);
    
    PROCEDURE SP_MANTER_GRUPO_ADMIN_INTEGRACAO (
        P_ID                             IN OUT CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE, 
        P_DS_GRUPO                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.DS_GRUPO%TYPE,
        P_NM_CANAL                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_CANAL%TYPE,
        P_NM_CHAVE                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_CHAVE%TYPE,
        P_NM_ATIVO                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_ATIVO%TYPE,
        P_NM_USUARIO_ULTIMA_ATUALIZACAO  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_USUARIO_ULTIMA_ATUALIZACAO%TYPE,
        P_FL_TIPOINTEGRACAO              IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
		P_RETORNO        OUT NUMBER);
        
    PROCEDURE SP_MANTER_GRUPO_DN_ADMIN_INTEGRACAO (
        P_ID            IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.ID%TYPE, 
        P_CD_GRUPO      IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_GRUPO%TYPE,
        P_CD_REGIONAL   IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_REGIONAL%TYPE,
        P_DS_REGIONAL   IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.DS_REGIONAL%TYPE,
        P_CD_DN         IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_DN%TYPE,
        P_DS_DN         IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.DS_DN%TYPE,
        P_CD_MONTADORA  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_MONTADORA%TYPE,
        P_DS_MONTADORA  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.DS_MONTADORA%TYPE,
		P_RETORNO       OUT NUMBER);
        
    PROCEDURE SP_LISTAR_GRUPOS_ADMIN_INTEGRACAO (
      P_ID IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE,
      P_FL_TIPOINTEGRACAO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
      P_RETORNO	 OUT SYS_REFCURSOR);
      
   PROCEDURE SP_LISTAR_GRUPO_DN_ADMIN_INTEGRACAO (
      P_CD_GRUPO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.ID%TYPE,
      P_RETORNO	 OUT SYS_REFCURSOR);
      
    PROCEDURE SP_EXCLUIR_GRUPO_ADMIN_INTEGRACAO (
      P_ID                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE,
      P_NM_USUARIO_ULTIMA_ATUALIZACAO  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_USUARIO_ULTIMA_ATUALIZACAO%TYPE,
      P_RETORNO                        OUT NUMBER);
      
    PROCEDURE SP_VALIDAR_CHAVE_EXISTENTE_GRUPO_DN_ADMIN_INTEGRACAO (
      P_NM_CHAVE          IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_CHAVE%TYPE,
      P_FL_TIPOINTEGRACAO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
      P_RETORNO	 OUT SYS_REFCURSOR);
	  
    PROCEDURE SP_VALIDAR_DN_EXISTENTE_GRUPO_DN_ADMIN_INTEGRACAO (
      P_ID                IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE,
      P_CD_DN             IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_DN%TYPE,
      P_FL_TIPOINTEGRACAO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
      P_RETORNO	          OUT SYS_REFCURSOR);
      
    PROCEDURE SP_EXCLUIR_GRUPO_DN_ADMIN_INTEGRACAO (
      P_CD_GRUPO  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_GRUPO%TYPE,
      P_CD_DN     IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_DN%TYPE,
      P_RETORNO	  OUT NUMBER);

    PROCEDURE SP_OBTER_REMARKETING_CONFIG(
        P_ID_CONFIG IN  CADPD_OWN.FES_REMARKETING_CONFIG.ID_CONFIG%TYPE DEFAULT NULL,
        P_RETORNO    OUT SYS_REFCURSOR
    );

    PROCEDURE SP_OBTER_REMARKETING_ESTOQUE(
        P_ID IN  CADPD_OWN.FES_REMARKETING_ESTOQUE.ID%TYPE,
        P_ID_CONFIG IN  CADPD_OWN.FES_REMARKETING_ESTOQUE.ID_CONFIG%TYPE,
        P_NR_CNPJ IN  CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_CNPJ%TYPE,
        P_RETORNO   OUT SYS_REFCURSOR
    );

    PROCEDURE SP_OBTER_REMARKETING_PARAMETROS(
        P_ID_CONFIG IN  CADPD_OWN.FES_REMARKETING_PARAMETROS.ID_CONFIG%TYPE DEFAULT NULL,
        P_CD_DN     IN  CADPD_OWN.FES_REMARKETING_PARAMETROS.CD_DN%TYPE DEFAULT NULL,
        P_RETORNO    OUT SYS_REFCURSOR
    );

    PROCEDURE SP_MANTER_REMARKETING_CONFIG(
        P_ID_CONFIG            IN OUT CADPD_OWN.FES_REMARKETING_CONFIG.ID_CONFIG%TYPE,
        P_DT_VALIDADE_OFERTA   IN     CADPD_OWN.FES_REMARKETING_CONFIG.DT_VALIDADE_OFERTA%TYPE,
        P_FL_UPLOAD_ARQUIVO    IN     CADPD_OWN.FES_REMARKETING_CONFIG.FL_UPLOAD_ARQUIVO%TYPE,
        P_FL_DOWNLOAD_ARQUIVO  IN     CADPD_OWN.FES_REMARKETING_CONFIG.FL_DOWNLOAD_ARQUIVO%TYPE,
        P_FL_OFERTA_ENCERRADA  IN     CADPD_OWN.FES_REMARKETING_CONFIG.FL_OFERTA_ENCERRADA%TYPE,
        P_NM_USUARIO_ALTERACAO IN     CADPD_OWN.FES_REMARKETING_CONFIG.NM_USUARIO_ALTERACAO%TYPE,
        P_DT_INICIO_OFERTA     IN     CADPD_OWN.FES_REMARKETING_CONFIG.DT_INICIO_OFERTA%TYPE,
		P_RETORNO              OUT    SYS_REFCURSOR
    );

    PROCEDURE SP_MANTER_REMARKETING_ESTOQUE(
        P_ID                   IN OUT CADPD_OWN.FES_REMARKETING_ESTOQUE.ID%TYPE,
        P_ID_CONFIG            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.ID_CONFIG%TYPE,
        P_NM_PLACA             IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,
        P_NM_MODELO            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
        P_VL_FIPE              IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.VL_FIPE%TYPE,
        P_NR_HODOMETRO         IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_HODOMETRO%TYPE,
        P_NM_COR               IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_COR%TYPE,
        P_NR_ANO_MODELO        IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_ANO_MODELO%TYPE,
        P_DS_LAUDO_CAUTELAR    IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.DS_LAUDO_CAUTELAR_LINK%TYPE,
        P_VL_VENDA             IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.VL_VENDA%TYPE,
        P_NM_CIDADE            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
        P_NM_UF                IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
        P_FL_RESERVA           IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.FL_RESERVA%TYPE,
        P_CD_DN                IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.CD_DN%TYPE,
        P_NR_CNPJ              IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_CNPJ%TYPE,
        P_NM_USER_RESERVA      IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_USER_RESERVA%TYPE,
        P_DT_COMPRA            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.DT_COMPRA%TYPE,
        P_TP_FATURAMENTO       IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.TP_FATURAMENTO%TYPE,
		P_RETORNO              OUT    NUMBER
    );

    PROCEDURE SP_MANTER_REMARKETING_PARAMETROS(
        P_ID                IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS.ID%TYPE,
        P_ID_CONFIG         IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.ID_CONFIG%TYPE,
        P_NR_CNPJ           IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.NR_CNPJ%TYPE,
        P_CD_DN             IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.CD_DN%TYPE,
        P_NM_USUARIOS       IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.NM_USUARIOS%TYPE,
        P_QT_LIMITE_CARROS  IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.QT_LIMITE_CARROS%TYPE,
        P_VL_LIMITE			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.VL_LIMITE%TYPE,
		P_RETORNO           OUT    NUMBER
	);
	
    PROCEDURE SP_EXPURGO_REMARKETING(
        P_TIPO_EXPURGO IN VARCHAR2 DEFAULT 'TODOS'
    );

--REMARKETING II

    PROCEDURE SP_OBTER_REMARKETING_CONFIG_EXIBICAO( 
        P_CD_DN     IN  CADPD_OWN.FES_REMARKETING_PARAMETROS.CD_DN%TYPE,
        P_RETORNO   OUT SYS_REFCURSOR
    );
    
    PROCEDURE SP_OBTER_REMARKETING_UF_CIDADE(
        P_RETORNO   OUT SYS_REFCURSOR
    );
    
    PROCEDURE SP_OBTER_REMARKETING_LISTA_VEICULOS(
        P_CD_DN           IN CADPD_OWN.FES_REMARKETING_ESTOQUE.CD_DN%TYPE,
        P_NM_CIDADE       IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE DEFAULT NULL,
        P_NM_UF           IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE DEFAULT NULL,
        P_NM_MODELO          IN VARCHAR2 DEFAULT NULL,
        P_NM_PLACA           IN VARCHAR2 DEFAULT NULL,
        P_FL_STATUS       IN VARCHAR2 DEFAULT 'T',
		P_QT_ITENS_PAGINA IN OUT NUMBER,
        P_NR_PAGINA       IN OUT NUMBER,
        P_RETORNO         OUT SYS_REFCURSOR
    ) ;

--ADMIN_PARCEIRO_LOCACAO    

    PROCEDURE SP_OBTER_ADMIN_PARCEIRO_LOCACAO
    (
        P_ID_ADMIN_PARCEIRO_LOCACAO IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.ID_ADMIN_PARCEIRO_LOCACAO%TYPE DEFAULT NULL,
        P_CD_CONCESSIONARIA         IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.CD_CONCESSIONARIA%TYPE DEFAULT NULL,
        P_FL_ESTADO_USO             IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.FL_ESTADO_USO%TYPE DEFAULT NULL,
        P_RETORNO                   OUT SYS_REFCURSOR
    );
    
    PROCEDURE SP_MANTER_ADMIN_PARCEIRO_LOCACAO
    (
        P_ID_ADMIN_PARCEIRO_LOCACAO IN OUT CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.ID_ADMIN_PARCEIRO_LOCACAO%TYPE,
        P_FL_ESTADO_USO             IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.FL_ESTADO_USO%TYPE,
        P_DS_USUARIO                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.DS_USUARIO%TYPE,
        P_DS_ANO_MODELO             IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.DS_ANO_MODELO%TYPE,
        P_CD_CONCESSIONARIA         IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.CD_CONCESSIONARIA%TYPE,
        P_NR_PLANO_1                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.NR_PLANO_1%TYPE,
        P_NR_PLANO_2                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.NR_PLANO_2%TYPE,
        P_NR_PLANO_3                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.NR_PLANO_3%TYPE,
        P_RETORNO                   OUT    SYS_REFCURSOR
    );
    
    
    PROCEDURE SP_EXCLUIR_ADMIN_PARCEIRO_LOCACAO
    (
        P_CD_CONCESSIONARIA         IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.CD_CONCESSIONARIA%TYPE,
        P_DS_USUARIO                IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.DS_USUARIO%TYPE,
        P_RETORNO                   OUT SYS_REFCURSOR
    );
	
	
	PROCEDURE SP_OBTER_MODELO(
        P_NM_UF     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
		P_NM_CIDADE IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
		P_NM_PLACA  IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,
		P_RETORNO    OUT SYS_REFCURSOR
    );
	
	PROCEDURE SP_OBTER_PLACA(
        P_NM_UF     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
		P_NM_CIDADE IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
		P_NM_MODELO  IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
		P_RETORNO    OUT SYS_REFCURSOR
    );
	
	PROCEDURE SP_OBTER_UF(
        P_NM_MODELO     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
		P_NM_PLACA      IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,	
		P_NM_CIDADE     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
		P_RETORNO    OUT SYS_REFCURSOR
    );
	
	PROCEDURE SP_OBTER_CIDADE(
		P_NM_UF         IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
        P_NM_MODELO     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
		P_NM_PLACA      IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,		
		P_RETORNO    OUT SYS_REFCURSOR
    );
	
	
--NOVOS PARAMETROS DE REMARKETING (DN - GRUPODN - CATEG_VEIC - CALC)

PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_DN(
        P_ID						IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.ID%TYPE,
		P_CD_DN             		IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.CD_DN%TYPE,
		P_NR_CNPJ           	    IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.NR_CNPJ%TYPE,    
		P_NM_USUARIOS_COMPRA        IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.NM_USUARIOS_COMPRA%TYPE,
		P_NM_USUARIOS_RELATORIO     IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.NM_USUARIOS_RELATORIO%TYPE,
		P_RETORNO           		OUT    NUMBER
	);
	
PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_GRUPO_DN(
		P_ID                   			IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.ID%TYPE,                   
		P_NM_GRUPO             			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.NM_GRUPO%TYPE,             	
		P_NM_CATEGORIA         			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.NM_CATEGORIA%TYPE,         	
		P_DS_CATEGORIA         			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.DS_CATEGORIA%TYPE,         	
		P_CD_DN                			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.CD_DN%TYPE,                	
		P_QT_LIMITE_TP_FATURAMENTO		IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.QT_LIMITE_TP_FATURAMENTO%TYPE,
		P_VL_LIMITE_TP_FATURAMENTO 		IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.VL_LIMITE_TP_FATURAMENTO%TYPE,
		P_TP_FATURAMENTO                IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.TP_FATURAMENTO%TYPE,          
		P_RETORNO			 			OUT    NUMBER
	);
	
PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_CATEGORIA_VEICULO (
		P_ID            IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO.ID%TYPE,
		P_NM_CATEGORIA  IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO.NM_CATEGORIA%TYPE,
		P_DS_CATEGORIA  IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO.DS_CATEGORIA%TYPE,
		P_RETORNO       OUT    NUMBER
);

PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_CALC (
    P_ID                         IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.ID%TYPE,
    P_NM_GRUPO_DN                IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.NM_GRUPO_DN%TYPE,
    P_DS_GRUPO_DN                IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.DS_GRUPO_DN%TYPE,
    P_QT_LIMITE_DESCONTO         IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.QT_LIMITE_DESCONTO%TYPE,
    P_VL_LIMITE_DESCONTO         IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.VL_LIMITE_DESCONTO%TYPE,
    P_QT_DESCONTO_VEICULO_B      IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.QT_DESCONTO_VEICULO_B%TYPE,
    P_QT_DESCONTO_VEICULO_C      IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.QT_DESCONTO_VEICULO_C%TYPE,
    P_RETORNO                    OUT    NUMBER
);

PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_DN(
	P_CD_DN     IN  CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.CD_DN%TYPE,
	P_RETORNO   OUT SYS_REFCURSOR
);
	
PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_GRUPO_DN(
	P_RETORNO    OUT SYS_REFCURSOR
);
	
PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_CATEGORIA_VEICULO (
	P_RETORNO    OUT SYS_REFCURSOR
);

PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_CALC (
	P_RETORNO    OUT SYS_REFCURSOR
);


END PG_FRONT_END_SYSTEM;
/
CREATE OR REPLACE PACKAGE BODY CADPD_OWN.PG_FRONT_END_SYSTEM
AS
    PROCEDURE SP_LISTAR_FES_CFG_COMUNICACAO_FUNCAO (P_RETORNO OUT SYS_REFCURSOR)
    IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT ID AS CODIGO, 
                   DESCRICAO
              FROM CADPD_OWN.FES_CFG_COMUNICACAO_FUNCAO;
    EXCEPTION
        WHEN OTHERS
        THEN
            RAISE_APPLICATION_ERROR (
                -20001,
                'PROBLEMAS NA LISTAGEM DA TABELA FES_CFG_COMUNICACAO_FUNCAO'
                || CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_LISTAR_FES_CFG_COMUNICACAO_FUNCAO;

	PROCEDURE SP_MANTER_COMUNICA_CONCESSIONARIA (
		P_ID                IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.ID%TYPE,
		P_CD_CONCESSIONARIA IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_CONCESSIONARIA%TYPE,
		P_DS_CONCESSIONARIA IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_CONCESSIONARIA%TYPE,
		P_CD_REGIONAL       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_REGIONAL%TYPE,
		P_DS_REGIONAL       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_REGIONAL%TYPE,
		P_CD_MONTADORA      IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_MONTADORA%TYPE,
		P_DS_MONTADORA      IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_MONTADORA%TYPE,
		P_CD_FUNCAO         IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_FUNCAO%TYPE,
		P_DS_NOME           IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_NOME%TYPE,
		P_NM_TELEFONE       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.NM_TELEFONE%TYPE,
		P_DS_EMAIL          IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_EMAIL%TYPE,
		P_DS_USUARIO        IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DS_USUARIO%TYPE,
		P_FL_EMAIL_BANCO    IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_EMAIL_BANCO%TYPE,
		P_FL_EMAIL_NF       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_EMAIL_NF%TYPE,
		P_FL_PESQUISA       IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_PESQUISA%TYPE,
		P_FL_NEGOCIACAO     IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.FL_NEGOCIACAO%TYPE
	) AS
	BEGIN
		MERGE INTO CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA TGT
		USING (SELECT P_ID AS ID FROM DUAL) SRC
		ON (TGT.ID = SRC.ID)
		WHEN MATCHED THEN
			UPDATE SET 
				CD_CONCESSIONARIA = P_CD_CONCESSIONARIA,
				DS_CONCESSIONARIA = P_DS_CONCESSIONARIA,
				CD_REGIONAL = P_CD_REGIONAL,
				DS_REGIONAL = P_DS_REGIONAL,
				CD_MONTADORA = P_CD_MONTADORA,
				DS_MONTADORA = P_DS_MONTADORA,
				CD_FUNCAO = P_CD_FUNCAO,
				DS_NOME = P_DS_NOME,
				NM_TELEFONE = P_NM_TELEFONE,
				DS_EMAIL = P_DS_EMAIL,
				DS_USUARIO = P_DS_USUARIO,
				FL_EMAIL_BANCO = P_FL_EMAIL_BANCO,
				FL_EMAIL_NF = P_FL_EMAIL_NF,
				FL_PESQUISA = P_FL_PESQUISA,
				FL_NEGOCIACAO = P_FL_NEGOCIACAO,
				DT_ULTIMA_EDICAO = SYSDATE
		WHEN NOT MATCHED THEN
			INSERT (
				CD_CONCESSIONARIA,
				DS_CONCESSIONARIA,
				CD_REGIONAL,
				DS_REGIONAL,
				CD_MONTADORA,
				DS_MONTADORA,
				CD_FUNCAO,
				DS_NOME,
				NM_TELEFONE,
				DS_EMAIL,
				DS_USUARIO,
				FL_EMAIL_BANCO,
				FL_EMAIL_NF,
				FL_PESQUISA,
				FL_NEGOCIACAO,
				DT_CADASTRO,
				DT_ULTIMA_EDICAO
			) VALUES (
				P_CD_CONCESSIONARIA,
				P_DS_CONCESSIONARIA,
				P_CD_REGIONAL,
				P_DS_REGIONAL,
				P_CD_MONTADORA,
				P_DS_MONTADORA,
				P_CD_FUNCAO,
				P_DS_NOME,
				P_NM_TELEFONE,
				P_DS_EMAIL,
				P_DS_USUARIO,
				P_FL_EMAIL_BANCO,
				P_FL_EMAIL_NF,
				P_FL_PESQUISA,
				P_FL_NEGOCIACAO,
				SYSDATE,
				SYSDATE
			);
	EXCEPTION
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR (
				-20002,
				'PROBLEMAS AO MANTER COMUNICAÇÃO COM DN' 
				|| CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_MANTER_COMUNICA_CONCESSIONARIA;

	PROCEDURE SP_EXCLUIR_COMUNICA_CONCESSIONARIA (
		P_ID IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.ID%TYPE
	) AS
	BEGIN
		UPDATE CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA
		SET DT_EXCLUSAO = SYSDATE
		WHERE ID = P_ID
		  AND DT_EXCLUSAO IS NULL;

		IF SQL%ROWCOUNT = 0 THEN
			RAISE_APPLICATION_ERROR(-20002, 'REGISTRO NÃO ENCONTRADO OU JÁ EXCLUÍDO.');
		END IF;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR (
				-20001,
				'PROBLEMAS AO EXCLUIR COMUNICAÇÃO COM DN' 
				|| CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_EXCLUIR_COMUNICA_CONCESSIONARIA;	

	PROCEDURE SP_LISTAR_COMUNICA_CONCESSIONARIA (
		P_CD_CONCESSIONARIA		IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.CD_CONCESSIONARIA%TYPE,
		P_DATA_INICIO         	IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DT_CADASTRO%TYPE,
		P_DATA_FIM            	IN CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA.DT_CADASTRO%TYPE,
		P_RETORNO 				OUT SYS_REFCURSOR
	) AS
	BEGIN
		OPEN P_RETORNO FOR
		SELECT
			ID, 
			CD_CONCESSIONARIA, 
			DS_CONCESSIONARIA, 
			CD_REGIONAL, 
			DS_REGIONAL, 
			CD_MONTADORA, 
			DS_MONTADORA, 
			CD_FUNCAO, 
			DS_NOME, 
			NM_TELEFONE, 
			DS_EMAIL, 
			DS_USUARIO, 
			FL_EMAIL_BANCO, 
			FL_EMAIL_NF, 
			FL_PESQUISA, 
			FL_NEGOCIACAO, 
			DT_CADASTRO, 
			DT_ULTIMA_EDICAO
		FROM CADPD_OWN.FES_CFG_COMUNICACAO_CONCESSIONARIA
		WHERE 
			CD_CONCESSIONARIA = P_CD_CONCESSIONARIA
			AND DT_CADASTRO >= P_DATA_INICIO
			AND DT_CADASTRO <= P_DATA_FIM
			AND DT_EXCLUSAO IS NULL;		  
	EXCEPTION
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR (
				-20001,
				'PROBLEMAS AO OBTER COMUNICAÇÃO COM DN' 
				|| CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_LISTAR_COMUNICA_CONCESSIONARIA;
	
	PROCEDURE SP_MANTER_AVALIACAO_CORRESPONDENTE_PAIS (
       P_ID                   IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.ID%TYPE,
        P_CD_USUARIO           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_USUARIO%TYPE,
        P_DS_USUARIO           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_USUARIO%TYPE,
        P_CD_CONCESSIONARIA    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_CONCESSIONARIA%TYPE,
        P_DS_CONCESSIONARIA    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_CONCESSIONARIA%TYPE,
        P_CD_REGIONAL          IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_REGIONAL%TYPE,
        P_DS_REGIONAL          IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_REGIONAL%TYPE,
        P_CD_MONTADORA         IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_MONTADORA%TYPE,
        P_DS_MONTADORA         IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_MONTADORA%TYPE,
        P_NM_NOME              IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.NM_NOME%TYPE,
        P_NR_CPF               IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.NR_CPF%TYPE,
        P_DS_EMAIL             IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DS_EMAIL%TYPE,
        P_NR_CERTIFICADO       IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.NR_CERTIFICADO%TYPE,
        P_DT_EMISSAO           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_EMISSAO%TYPE,
        P_DT_VENCIMENTO        IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_VENCIMENTO%TYPE,
        P_FL_CRACHA_VISIVEL    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CRACHA_VISIVEL%TYPE,
        P_FL_CREDITO_LOGISTA   IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CREDITO_LOGISTA%TYPE,
        P_FL_CREDITO_SITE      IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CREDITO_SITE%TYPE,
        P_FL_CORRESPONDENTE    IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_CORRESPONDENTE%TYPE,
        P_FL_COBRANCA_CET      IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.FL_COBRANCA_CET%TYPE
    ) AS
    BEGIN
        MERGE INTO CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS TGT
        USING (SELECT P_ID AS ID FROM DUAL) SRC
        ON (TGT.ID = SRC.ID)
        WHEN MATCHED THEN
            UPDATE SET 
                CD_USUARIO = P_CD_USUARIO,
                DS_USUARIO = P_DS_USUARIO,
                CD_CONCESSIONARIA = P_CD_CONCESSIONARIA,
                DS_CONCESSIONARIA = P_DS_CONCESSIONARIA,
                CD_REGIONAL = P_CD_REGIONAL,
                DS_REGIONAL = P_DS_REGIONAL,
                DS_MONTADORA = P_DS_MONTADORA,
                CD_MONTADORA = P_CD_MONTADORA,
                NM_NOME = P_NM_NOME,
                NR_CPF = P_NR_CPF,
                DS_EMAIL = P_DS_EMAIL,
                NR_CERTIFICADO = P_NR_CERTIFICADO,
                DT_EMISSAO = P_DT_EMISSAO,
                DT_VENCIMENTO = P_DT_VENCIMENTO,
                FL_CRACHA_VISIVEL = P_FL_CRACHA_VISIVEL,
                FL_CREDITO_LOGISTA = P_FL_CREDITO_LOGISTA,
                FL_CREDITO_SITE = P_FL_CREDITO_SITE,
                FL_CORRESPONDENTE = P_FL_CORRESPONDENTE,
                FL_COBRANCA_CET = P_FL_COBRANCA_CET,
                DT_ULTIMA_EDICAO = SYSDATE
        WHEN NOT MATCHED THEN
            INSERT (
				ID, DT_CADASTRO, CD_USUARIO, DS_USUARIO, CD_CONCESSIONARIA, DS_CONCESSIONARIA, 
				CD_REGIONAL, DS_REGIONAL, DS_MONTADORA, CD_MONTADORA, NM_NOME, NR_CPF, DS_EMAIL, 
				NR_CERTIFICADO, DT_EMISSAO, DT_VENCIMENTO, FL_CRACHA_VISIVEL, FL_CREDITO_LOGISTA, 
				FL_CREDITO_SITE, FL_CORRESPONDENTE, FL_COBRANCA_CET, DT_ULTIMA_EDICAO
			) VALUES (
				P_ID, SYSDATE, P_CD_USUARIO, P_DS_USUARIO, P_CD_CONCESSIONARIA, P_DS_CONCESSIONARIA, 
				P_CD_REGIONAL, P_DS_REGIONAL, P_DS_MONTADORA, P_CD_MONTADORA, P_NM_NOME, P_NR_CPF, P_DS_EMAIL, 
				P_NR_CERTIFICADO, P_DT_EMISSAO, P_DT_VENCIMENTO, P_FL_CRACHA_VISIVEL, P_FL_CREDITO_LOGISTA, 
				P_FL_CREDITO_SITE, P_FL_CORRESPONDENTE, P_FL_COBRANCA_CET, SYSDATE
			);
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR (
                -20002,
                'PROBLEMAS AO MANTER AVALIAÇÃO CORRESPONDENTE' 
                || CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_AVALIACAO_CORRESPONDENTE_PAIS;
	
	PROCEDURE SP_EXCLUIR_AVALIACAO_CORRESPONDENTE (
        P_ID IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.ID%TYPE
    ) AS
    BEGIN
        UPDATE CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS
        SET DT_EXCLUSAO = SYSDATE
        WHERE ID = P_ID
          AND DT_EXCLUSAO IS NULL;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'REGISTRO NÃO ENCONTRADO OU JÁ EXCLUÍDO.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR (
                -20001,
                'PROBLEMAS AO EXCLUIR AVALIAÇÃO CORRESPONDENTE' 
                || CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_EXCLUIR_AVALIACAO_CORRESPONDENTE;
	
	PROCEDURE SP_LISTAR_AVALIACAO_CORRESPONDENTE (
        P_CD_CONCESSIONARIA  IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.CD_CONCESSIONARIA%TYPE,
        P_DATA_INICIO        IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_CADASTRO%TYPE,
        P_DATA_FIM           IN CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS.DT_CADASTRO%TYPE,
        P_RETORNO            OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RETORNO FOR
        SELECT
            ID, 
			CD_USUARIO, 
			DS_USUARIO, 
			CD_CONCESSIONARIA, 
			DS_CONCESSIONARIA, 
			CD_REGIONAL, 
			DS_REGIONAL, 
			CD_MONTADORA, 
			DS_MONTADORA, 
			NM_NOME, 
			NR_CPF, 
			DS_EMAIL, 
			NR_CERTIFICADO, 
			DT_EMISSAO, 
			DT_VENCIMENTO, 
			FL_CRACHA_VISIVEL, 
			FL_CREDITO_LOGISTA, 
			FL_CREDITO_SITE, 
			FL_CORRESPONDENTE, 
			FL_COBRANCA_CET, 
			DT_CADASTRO, 
			DT_ULTIMA_EDICAO
        FROM CADPD_OWN.FES_AVALIACAO_CORRESPONDENTE_PAIS
        WHERE 
            CD_CONCESSIONARIA = P_CD_CONCESSIONARIA
            AND DT_CADASTRO >= P_DATA_INICIO
            AND DT_CADASTRO <= P_DATA_FIM
            AND DT_EXCLUSAO IS NULL;  
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR (
                -20001,
                'PROBLEMAS AO OBTER AVALIAÇÃO CORRESPONDENTE' 
                || CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_LISTAR_AVALIACAO_CORRESPONDENTE;

	PROCEDURE SP_MANTER_PILOTO (
		P_ID             IN CADPD_OWN.FES_PILOTO.ID%TYPE, 
		P_CD_IDDESCRICAO IN CADPD_OWN.FES_PILOTO.CD_IDDESCRICAO%TYPE,
		P_CD_DN          IN CADPD_OWN.FES_PILOTO.CD_DN%TYPE,
		P_CD_EMPRESA     IN CADPD_OWN.FES_PILOTO.CD_EMPRESA%TYPE,
		P_DT_INICIO      IN CADPD_OWN.FES_PILOTO.DT_INICIO%TYPE,
		P_DT_FIM         IN CADPD_OWN.FES_PILOTO.DT_FIM%TYPE,
		P_RETORNO        OUT NUMBER)
	   IS
	   BEGIN
		   MERGE INTO CADPD_OWN.FES_PILOTO FP
		  USING (SELECT P_ID AS ID FROM DUAL) SRC
            ON (FP.ID = SRC.ID)
		  WHEN MATCHED THEN
            UPDATE SET 
                CD_IDDESCRICAO = P_CD_IDDESCRICAO,
                CD_DN = P_CD_DN,
                CD_EMPRESA = P_CD_EMPRESA,
                DT_INICIO = SYSDATE,
                DT_FIM = (ADD_MONTHS(SYSDATE, 12))
          WHEN NOT MATCHED THEN
                INSERT (
					ID,
					CD_IDDESCRICAO,
					CD_DN,
					CD_EMPRESA,
					DT_INICIO,
					DT_FIM
				) VALUES (
					(SELECT NVL(MAX(ID), 0) + 1 FROM CADPD_OWN.FES_PILOTO),
					P_CD_IDDESCRICAO,
					P_CD_DN,
					P_CD_EMPRESA,
					SYSDATE,
					(ADD_MONTHS(SYSDATE, 12))
				);

            SELECT P_ID INTO P_Retorno
			FROM DUAL;
	   EXCEPTION
		  WHEN OTHERS
		  THEN
			 RAISE_APPLICATION_ERROR (
				-20001,
				   'PROBLEMAS AO MANTER PILOTO'
				|| CHR (13)
				|| 'SQLERRM: '
				|| SQLERRM
				|| CHR (13)
				|| 'ERROR_STACK: '
				|| DBMS_UTILITY.FORMAT_ERROR_STACK
				|| CHR (13)
				|| 'ERROR_BACKTRACE: '
				|| DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_PILOTO;

	PROCEDURE SP_MANTER_PILOTO_DESCRICAO (
		P_ID             IN CADPD_OWN.FES_DESC_PILOTO.ID%TYPE, 
		P_NM_NOME        IN CADPD_OWN.FES_DESC_PILOTO.NM_NOME%TYPE,
		P_DS_DESCRICAO   IN CADPD_OWN.FES_DESC_PILOTO.DS_DESCRICAO%TYPE,
		P_FL_ATIVO       IN CADPD_OWN.FES_DESC_PILOTO.FL_ATIVO%TYPE,
		P_RETORNO        OUT NUMBER)
	   IS
	   BEGIN
		  MERGE INTO CADPD_OWN.FES_DESC_PILOTO
			   USING DUAL
				  ON (ID = P_ID)
		  WHEN MATCHED THEN
			 UPDATE SET 
					NM_NOME = P_NM_NOME,
					DS_DESCRICAO = P_DS_DESCRICAO,
					FL_ATIVO = P_FL_ATIVO
		  WHEN NOT MATCHED THEN
            INSERT (
					ID,
					NM_NOME,
					DS_DESCRICAO,
					FL_ATIVO
				) VALUES (
					(SELECT NVL(MAX(ID), 0) + 1 FROM CADPD_OWN.FES_DESC_PILOTO),
					P_NM_NOME,
					P_DS_DESCRICAO,
					P_FL_ATIVO
				);

			SELECT ID INTO P_RETORNO
			FROM CADPD_OWN.FES_DESC_PILOTO
			WHERE ID = P_ID;
	   EXCEPTION
		  WHEN OTHERS
		  THEN
			 RAISE_APPLICATION_ERROR (
				-20001,
				   'PROBLEMAS AO MANTER PILOTO DESCRICAO'
				|| CHR (13)
				|| 'SQLERRM: '
				|| SQLERRM
				|| CHR (13)
				|| 'ERROR_STACK: '
				|| DBMS_UTILITY.FORMAT_ERROR_STACK
				|| CHR (13)
				|| 'ERROR_BACKTRACE: '
				|| DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_MANTER_PILOTO_DESCRICAO;

	PROCEDURE SP_LISTAR_PILOTOS (
		  P_CD_IDDESCRICAO IN CADPD_OWN.FES_PILOTO.CD_IDDESCRICAO%TYPE,
		  P_RETORNO				OUT SYS_REFCURSOR)
		IS
		BEGIN
		  OPEN P_RETORNO FOR
			 SELECT ID,
					CD_IDDESCRICAO,
					CD_DN,
					CD_EMPRESA,
					DT_INICIO,
					DT_FIM
			   FROM  CADPD_OWN.FES_PILOTO
			  WHERE CD_IDDESCRICAO = P_CD_IDDESCRICAO;
		EXCEPTION
		  WHEN OTHERS
		  THEN
			 RAISE_APPLICATION_ERROR (
				-20001,
				   'PROBLEMAS AO OBTER LISTA DO PILOTO'
				|| CHR (13)
				|| 'SQLERRM: '
				|| SQLERRM
				|| CHR (13)
				|| 'ERROR_STACK: '
				|| DBMS_UTILITY.FORMAT_ERROR_STACK
				|| CHR (13)
				|| 'ERROR_BACKTRACE: '
				|| DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
		END SP_LISTAR_PILOTOS;	
		
    PROCEDURE SP_LISTAR_PILOTOS_DESCRICAO (
		  P_ID   IN CADPD_OWN.FES_DESC_PILOTO.ID%TYPE,
		  P_RETORNO				OUT SYS_REFCURSOR)
		IS
		BEGIN
		  OPEN P_RETORNO FOR
			 SELECT ID,
					NM_NOME,
					DS_DESCRICAO,
					FL_ATIVO
			   FROM  CADPD_OWN.FES_DESC_PILOTO
			  WHERE ID = P_ID;
		EXCEPTION
		  WHEN OTHERS
		  THEN
			 RAISE_APPLICATION_ERROR (
				-20001,
				   'PROBLEMAS AO OBTER LISTA DO PILOTO DESCRICAO'
				|| CHR (13)
				|| 'SQLERRM: '
				|| SQLERRM
				|| CHR (13)
				|| 'ERROR_STACK: '
				|| DBMS_UTILITY.FORMAT_ERROR_STACK
				|| CHR (13)
				|| 'ERROR_BACKTRACE: '
				|| DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
		END SP_LISTAR_PILOTOS_DESCRICAO;
		
    PROCEDURE SP_LISTAR_PILOTOS_POR_DN (
      P_CD_DN          IN CADPD_OWN.FES_PILOTO.CD_DN%TYPE,
      P_RETORNO		 OUT SYS_REFCURSOR)
    IS
    BEGIN
      OPEN P_RETORNO FOR
		SELECT FDP.ID,FDP.NM_NOME, FDP.DS_DESCRICAO,  FDP.FL_ATIVO,
			   CASE WHEN COUNT(CASE WHEN FPL.CD_DN = P_CD_DN THEN 1 END) > 0 THEN 'S' ELSE 'N' END AS DN_ATIVO
		  FROM CADPD_OWN.FES_DESC_PILOTO FDP
		 INNER JOIN CADPD_OWN.FES_PILOTO FPL ON FDP.ID = FPL.CD_IDDESCRICAO
		 WHERE FDP.FL_ATIVO = 'S'
		 GROUP BY FDP.ID, FDP.NM_NOME, FDP.DS_DESCRICAO, FDP.FL_ATIVO;
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
               'PROBLEMAS AO OBTER LISTA DO PILOTO DESCRICAO POR DN'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_LISTAR_PILOTOS_POR_DN;
	
	PROCEDURE SP_EXPURGO_PILOTO (
		P_CD_IDDESCRICAO    IN  CADPD_OWN.FES_PILOTO.CD_IDDESCRICAO%TYPE
		)
	IS
	BEGIN
		DELETE FROM CADPD_OWN.FES_PILOTO
					WHERE CD_IDDESCRICAO = P_CD_IDDESCRICAO;
			  COMMIT;   
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO EXPURGAR PILOTO.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_EXPURGO_PILOTO;
	
    PROCEDURE SP_MANTER_GRUPO_ADMIN_INTEGRACAO (
        P_ID                             IN OUT CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE, 
        P_DS_GRUPO                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.DS_GRUPO%TYPE,
        P_NM_CANAL                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_CANAL%TYPE,
        P_NM_CHAVE                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_CHAVE%TYPE,
        P_NM_ATIVO                       IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_ATIVO%TYPE,
        P_NM_USUARIO_ULTIMA_ATUALIZACAO  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_USUARIO_ULTIMA_ATUALIZACAO%TYPE,
        P_FL_TIPOINTEGRACAO              IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
		P_RETORNO                        OUT NUMBER)
	   IS
	   BEGIN
       
        IF P_ID IS NULL OR P_ID = 0 THEN
            P_ID := CADPD_OWN.FES_GRUPO_ADM_INTEG_ID_SEQ.NEXTVAL;
        END IF;

		P_RETORNO := P_ID;
       
         MERGE INTO CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO FP
         USING (SELECT P_FL_TIPOINTEGRACAO AS S_FL_TIPOINTEGRACAO,
                       P_NM_CHAVE          AS S_NM_CHAVE,
                       P_ID                AS S_ID
                  FROM DUAL) SPU
            ON (    FP.FL_TIPOINTEGRACAO = SPU.S_FL_TIPOINTEGRACAO 
                AND FP.NM_CHAVE          = SPU.S_NM_CHAVE
                AND FP.ID                = SPU.S_ID)
		  WHEN MATCHED THEN
            UPDATE SET
                DS_GRUPO                      = P_DS_GRUPO,
                NM_CANAL                      = P_NM_CANAL,
                NM_ATIVO                      = P_NM_ATIVO,
                DT_ULTIMA_ATUALIZACAO         = SYSDATE,
                NM_USUARIO_ULTIMA_ATUALIZACAO = P_NM_USUARIO_ULTIMA_ATUALIZACAO
          WHEN NOT MATCHED THEN
                INSERT (
                        ID,
                        DS_GRUPO,
                        NM_CANAL,
                        NM_CHAVE,
                        NM_ATIVO,
                        DT_ULTIMA_ATUALIZACAO,
                        NM_USUARIO_ULTIMA_ATUALIZACAO,
                        FL_TIPOINTEGRACAO
                    ) VALUES (
                        P_ID,
                        P_DS_GRUPO,
                        P_NM_CANAL,
                        P_NM_CHAVE,
                        'S',
                        SYSDATE,
                        P_NM_USUARIO_ULTIMA_ATUALIZACAO,
                        P_FL_TIPOINTEGRACAO
                    );
                    
	   EXCEPTION
		  WHEN OTHERS
		  THEN
			 RAISE_APPLICATION_ERROR (
				-20001,
				   'PROBLEMAS AO MANTER GRUPO ADMIN INTEGRACAO'
				|| CHR (13)
				|| 'SQLERRM: '
				|| SQLERRM
				|| CHR (13)
				|| 'ERROR_STACK: '
				|| DBMS_UTILITY.FORMAT_ERROR_STACK
				|| CHR (13)
				|| 'ERROR_BACKTRACE: '
				|| DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_GRUPO_ADMIN_INTEGRACAO;
    
    PROCEDURE SP_MANTER_GRUPO_DN_ADMIN_INTEGRACAO (
        P_ID            IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.ID%TYPE, 
        P_CD_GRUPO      IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_GRUPO%TYPE,
        P_CD_REGIONAL   IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_REGIONAL%TYPE,
        P_DS_REGIONAL   IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.DS_REGIONAL%TYPE,
        P_CD_DN         IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_DN%TYPE,
        P_DS_DN         IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.DS_DN%TYPE,
        P_CD_MONTADORA  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_MONTADORA%TYPE,
        P_DS_MONTADORA  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.DS_MONTADORA%TYPE,
		P_RETORNO       OUT NUMBER)
	   IS
	   BEGIN
		  MERGE INTO CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN FP
		  USING (SELECT P_CD_DN AS CD_DN, P_CD_GRUPO AS CD_GRUPO  FROM DUAL) SRC
             ON (FP.CD_DN = SRC.CD_DN AND FP.CD_GRUPO = SRC.CD_GRUPO)
		  WHEN MATCHED THEN
            UPDATE SET 
                CD_REGIONAL   = P_CD_REGIONAL,
                DS_REGIONAL   = P_DS_REGIONAL,
                DS_DN         = P_DS_DN,
                CD_MONTADORA  = P_CD_MONTADORA,
                DS_MONTADORA  = P_DS_MONTADORA
          WHEN NOT MATCHED THEN
                INSERT (
                        ID,
                        CD_GRUPO,
                        CD_REGIONAL,
                        DS_REGIONAL,
                        CD_DN,
                        DS_DN,
                        CD_MONTADORA,
                        DS_MONTADORA
                    ) VALUES (
                        FES_GRUPO_ADM_INTEG_DN_ID_SEQ.NEXTVAL,
                        P_CD_GRUPO,
                        P_CD_REGIONAL,
                        P_DS_REGIONAL,
                        P_CD_DN,
                        P_DS_DN,
                        P_CD_MONTADORA,
                        P_DS_MONTADORA
                    );

            SELECT CADPD_OWN.FES_GRUPO_ADM_INTEG_DN_ID_SEQ.CURRVAL INTO P_Retorno
			FROM DUAL;
	   EXCEPTION
		  WHEN OTHERS
		  THEN
			 RAISE_APPLICATION_ERROR (
				-20001,
				   'PROBLEMAS AO MANTER GRUPO DN ADMIN INTEGRACAO'
				|| CHR (13)
				|| 'SQLERRM: '
				|| SQLERRM
				|| CHR (13)
				|| 'ERROR_STACK: '
				|| DBMS_UTILITY.FORMAT_ERROR_STACK
				|| CHR (13)
				|| 'ERROR_BACKTRACE: '
				|| DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_GRUPO_DN_ADMIN_INTEGRACAO;
    
    PROCEDURE SP_LISTAR_GRUPOS_ADMIN_INTEGRACAO (
      P_ID                IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE,
      P_FL_TIPOINTEGRACAO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
      P_RETORNO	          OUT SYS_REFCURSOR)
    IS
    BEGIN
      OPEN P_RETORNO FOR
        SELECT ID,DS_GRUPO,NM_CANAL,NM_CHAVE,CASE WHEN NM_ATIVO = 'S' THEN 1 ELSE 0 END AS NM_ATIVO ,DT_ULTIMA_ATUALIZACAO,NM_USUARIO_ULTIMA_ATUALIZACAO,FL_TIPOINTEGRACAO 
          FROM CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO
         WHERE (FL_TIPOINTEGRACAO = P_FL_TIPOINTEGRACAO OR P_FL_TIPOINTEGRACAO = 'TODOS')
           AND (ID =P_ID OR P_ID = -1)
           AND NM_ATIVO = 'S';
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
               'PROBLEMAS AO OBTER LISTA DO GRUPO ADMIN INTEGRACAO'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_LISTAR_GRUPOS_ADMIN_INTEGRACAO;
    
    PROCEDURE SP_LISTAR_GRUPO_DN_ADMIN_INTEGRACAO (
      P_CD_GRUPO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.ID%TYPE,
      P_RETORNO	 OUT SYS_REFCURSOR)
    IS
    BEGIN
      OPEN P_RETORNO FOR
        SELECT ID,CD_GRUPO,CD_REGIONAL,DS_REGIONAL,CD_DN,DS_DN,CD_MONTADORA,DS_MONTADORA
          FROM CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN
         WHERE CD_GRUPO = P_CD_GRUPO;
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
               'PROBLEMAS AO OBTER LISTA DO GRUPO DN ADMIN INTEGRACAO'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_LISTAR_GRUPO_DN_ADMIN_INTEGRACAO;
    
    PROCEDURE SP_EXCLUIR_GRUPO_ADMIN_INTEGRACAO (
      P_ID                             IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE,
      P_NM_USUARIO_ULTIMA_ATUALIZACAO  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_USUARIO_ULTIMA_ATUALIZACAO%TYPE,
      P_RETORNO                        OUT NUMBER)
    IS
    BEGIN
        UPDATE CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO
           SET NM_ATIVO = 'N',
               NM_USUARIO_ULTIMA_ATUALIZACAO = P_NM_USUARIO_ULTIMA_ATUALIZACAO,
               DT_ULTIMA_ATUALIZACAO = SYSDATE
         WHERE ID = P_ID;
         
         SELECT 1 INTO P_RETORNO 
           FROM DUAL;
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
            'PROBLEMAS AO EXCLUIR LISTA DO GRUPO DN ADMIN INTEGRACAO'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_EXCLUIR_GRUPO_ADMIN_INTEGRACAO;
    
    PROCEDURE SP_VALIDAR_CHAVE_EXISTENTE_GRUPO_DN_ADMIN_INTEGRACAO (
      P_NM_CHAVE          IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.NM_CHAVE%TYPE,
      P_FL_TIPOINTEGRACAO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
      P_RETORNO	 OUT SYS_REFCURSOR)
    IS
    BEGIN
      OPEN P_RETORNO FOR
        SELECT ID,DS_GRUPO,NM_CANAL,NM_CHAVE,CASE WHEN NM_ATIVO = 'S' THEN 1 ELSE 0 END AS NM_ATIVO ,DT_ULTIMA_ATUALIZACAO,NM_USUARIO_ULTIMA_ATUALIZACAO,FL_TIPOINTEGRACAO
          FROM CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO
         WHERE NM_CHAVE = P_NM_CHAVE
           AND NM_ATIVO = 'S'; 
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
               'PROBLEMAS AO VALIDAR CHAVE EXISTENTE DO GRUPO DN ADMIN INTEGRACAO'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_VALIDAR_CHAVE_EXISTENTE_GRUPO_DN_ADMIN_INTEGRACAO;
	
    PROCEDURE SP_VALIDAR_DN_EXISTENTE_GRUPO_DN_ADMIN_INTEGRACAO (
      P_ID                IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.ID%TYPE,
      P_CD_DN             IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_DN%TYPE,
      P_FL_TIPOINTEGRACAO IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO.FL_TIPOINTEGRACAO%TYPE,
      P_RETORNO	          OUT SYS_REFCURSOR)
    IS
    BEGIN
      OPEN P_RETORNO FOR
        SELECT GAI.DS_GRUPO, GAIN.CD_DN, GAIN.DS_DN, GAIN.CD_MONTADORA, GAIN.DS_MONTADORA  
          FROM FES_GRUPO_ADM_INTEGRACAO GAI 
               INNER JOIN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN GAIN ON GAI.ID = GAIN.CD_GRUPO
         WHERE GAIN.CD_DN = P_CD_DN
           AND GAI.ID <> P_ID
           AND GAI.FL_TIPOINTEGRACAO = P_FL_TIPOINTEGRACAO
           AND GAI.NM_ATIVO = 'S';
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
               'PROBLEMAS AO VALIDAR DN EXISTENTE DO GRUPO DN ADMIN INTEGRACAO'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_VALIDAR_DN_EXISTENTE_GRUPO_DN_ADMIN_INTEGRACAO;
    
    PROCEDURE SP_EXCLUIR_GRUPO_DN_ADMIN_INTEGRACAO (
      P_CD_GRUPO  IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_GRUPO%TYPE,
      P_CD_DN     IN CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN.CD_DN%TYPE,
      P_RETORNO	  OUT NUMBER)
    IS
    BEGIN
        DELETE FROM CADPD_OWN.FES_GRUPO_ADM_INTEGRACAO_DN
         WHERE CD_GRUPO = P_CD_GRUPO
           AND CD_DN = P_CD_DN;
           
           SELECT 1 INTO P_RETORNO FROM DUAL;
    EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (
            -20001,
               'PROBLEMAS EXCLUIR DN EXISTENTE DO GRUPO DN ADMIN INTEGRACAO'
            || CHR (13)
            || 'SQLERRM: '
            || SQLERRM
            || CHR (13)
            || 'ERROR_STACK: '
            || DBMS_UTILITY.FORMAT_ERROR_STACK
            || CHR (13)
            || 'ERROR_BACKTRACE: '
            || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_EXCLUIR_GRUPO_DN_ADMIN_INTEGRACAO;
	
---REMARKETING

    PROCEDURE SP_OBTER_REMARKETING_CONFIG(
        P_ID_CONFIG IN  CADPD_OWN.FES_REMARKETING_CONFIG.ID_CONFIG%TYPE DEFAULT NULL,
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT ID_CONFIG, DT_VALIDADE_OFERTA, FL_UPLOAD_ARQUIVO, FL_DOWNLOAD_ARQUIVO, 
                   FL_OFERTA_ENCERRADA, NM_USUARIO_ALTERACAO, DT_ALTERACAO, DT_INICIO_OFERTA
            FROM CADPD_OWN.FES_REMARKETING_CONFIG
            WHERE (ID_CONFIG = P_ID_CONFIG OR P_ID_CONFIG IS NULL);
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING CONFIG.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_CONFIG;

    PROCEDURE SP_OBTER_REMARKETING_ESTOQUE(
        P_ID IN  CADPD_OWN.FES_REMARKETING_ESTOQUE.ID%TYPE,
        P_ID_CONFIG IN  CADPD_OWN.FES_REMARKETING_ESTOQUE.ID_CONFIG%TYPE,
		P_NR_CNPJ IN  CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_CNPJ%TYPE,
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT ID, ID_CONFIG, NR_CNPJ, NM_PLACA, NM_MODELO, VL_FIPE, NR_HODOMETRO, NM_COR, 
                   NR_ANO_MODELO, DS_LAUDO_CAUTELAR_LINK, VL_VENDA, NM_CIDADE, NM_UF, 
                   FL_RESERVA, CD_DN, NM_USER_RESERVA, DT_COMPRA, TP_FATURAMENTO
            FROM CADPD_OWN.FES_REMARKETING_ESTOQUE
           WHERE (ID_CONFIG = P_ID_CONFIG OR P_ID_CONFIG IS NULL)
             AND (ID = P_ID OR P_ID IS NULL)
             AND (NR_CNPJ = P_NR_CNPJ OR P_NR_CNPJ IS NULL)
            ;
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING ESTOQUE.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_ESTOQUE;

    PROCEDURE SP_OBTER_REMARKETING_PARAMETROS(
        P_ID_CONFIG IN  CADPD_OWN.FES_REMARKETING_PARAMETROS.ID_CONFIG%TYPE DEFAULT NULL,
        P_CD_DN     IN  CADPD_OWN.FES_REMARKETING_PARAMETROS.CD_DN%TYPE DEFAULT NULL,
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT ID, ID_CONFIG, NR_CNPJ, CD_DN, NM_USUARIOS, QT_LIMITE_CARROS, VL_LIMITE
              FROM CADPD_OWN.FES_REMARKETING_PARAMETROS
             WHERE (ID_CONFIG = P_ID_CONFIG OR P_ID_CONFIG IS NULL)
               AND (CD_DN = P_CD_DN OR P_CD_DN IS NULL);
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING PARAMETROS.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_PARAMETROS;

    PROCEDURE SP_MANTER_REMARKETING_CONFIG(
        P_ID_CONFIG            IN OUT CADPD_OWN.FES_REMARKETING_CONFIG.ID_CONFIG%TYPE,
        P_DT_VALIDADE_OFERTA   IN     CADPD_OWN.FES_REMARKETING_CONFIG.DT_VALIDADE_OFERTA%TYPE,
        P_FL_UPLOAD_ARQUIVO    IN     CADPD_OWN.FES_REMARKETING_CONFIG.FL_UPLOAD_ARQUIVO%TYPE,
        P_FL_DOWNLOAD_ARQUIVO  IN     CADPD_OWN.FES_REMARKETING_CONFIG.FL_DOWNLOAD_ARQUIVO%TYPE,
        P_FL_OFERTA_ENCERRADA  IN     CADPD_OWN.FES_REMARKETING_CONFIG.FL_OFERTA_ENCERRADA%TYPE,
        P_NM_USUARIO_ALTERACAO IN     CADPD_OWN.FES_REMARKETING_CONFIG.NM_USUARIO_ALTERACAO%TYPE,
        P_DT_INICIO_OFERTA     IN     CADPD_OWN.FES_REMARKETING_CONFIG.DT_INICIO_OFERTA%TYPE,
		P_RETORNO              OUT    SYS_REFCURSOR
    ) IS
    BEGIN
        IF P_ID_CONFIG IS NULL THEN
           P_ID_CONFIG := CADPD_OWN.FES_REMARKETING_CONFIG_SEQ.NEXTVAL;
        END IF;

        MERGE INTO CADPD_OWN.FES_REMARKETING_CONFIG t
        USING (SELECT P_ID_CONFIG AS ID FROM DUAL) s
        ON (t.ID_CONFIG = s.ID)
        WHEN MATCHED THEN
            UPDATE SET DT_VALIDADE_OFERTA = P_DT_VALIDADE_OFERTA, 
                       FL_UPLOAD_ARQUIVO = P_FL_UPLOAD_ARQUIVO,
                       FL_DOWNLOAD_ARQUIVO = P_FL_DOWNLOAD_ARQUIVO, 
                       FL_OFERTA_ENCERRADA = P_FL_OFERTA_ENCERRADA,
                       NM_USUARIO_ALTERACAO = P_NM_USUARIO_ALTERACAO,
                       DT_ALTERACAO = SYSDATE,
					   DT_INICIO_OFERTA = P_DT_INICIO_OFERTA
        WHEN NOT MATCHED THEN
            INSERT (ID_CONFIG, 
					DT_VALIDADE_OFERTA, 
					FL_UPLOAD_ARQUIVO, 
					FL_DOWNLOAD_ARQUIVO, 
                    FL_OFERTA_ENCERRADA, 
					NM_USUARIO_ALTERACAO, 
					DT_ALTERACAO,
					DT_INICIO_OFERTA)
            VALUES (P_ID_CONFIG, 
			        P_DT_VALIDADE_OFERTA, 
					P_FL_UPLOAD_ARQUIVO, 
					P_FL_DOWNLOAD_ARQUIVO, 
                    P_FL_OFERTA_ENCERRADA, 
					P_NM_USUARIO_ALTERACAO, 
					SYSDATE,
					P_DT_INICIO_OFERTA);
        
        OPEN P_RETORNO FOR                    
          SELECT ID_CONFIG, DT_VALIDADE_OFERTA, FL_UPLOAD_ARQUIVO, FL_DOWNLOAD_ARQUIVO, 
                   FL_OFERTA_ENCERRADA, NM_USUARIO_ALTERACAO, DT_ALTERACAO, DT_INICIO_OFERTA
            FROM CADPD_OWN.FES_REMARKETING_CONFIG
            WHERE ID_CONFIG = P_ID_CONFIG;
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP MANTER REMARKETING USUARIOS.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_REMARKETING_CONFIG;

    PROCEDURE SP_MANTER_REMARKETING_ESTOQUE(
        P_ID                   IN OUT CADPD_OWN.FES_REMARKETING_ESTOQUE.ID%TYPE,
        P_ID_CONFIG            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.ID_CONFIG%TYPE,
        P_NM_PLACA             IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,
        P_NM_MODELO            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
        P_VL_FIPE              IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.VL_FIPE%TYPE,
        P_NR_HODOMETRO         IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_HODOMETRO%TYPE,
        P_NM_COR               IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_COR%TYPE,
        P_NR_ANO_MODELO        IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_ANO_MODELO%TYPE,
        P_DS_LAUDO_CAUTELAR    IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.DS_LAUDO_CAUTELAR_LINK%TYPE,
        P_VL_VENDA             IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.VL_VENDA%TYPE,
        P_NM_CIDADE            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
        P_NM_UF                IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
        P_FL_RESERVA           IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.FL_RESERVA%TYPE,
        P_CD_DN                IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.CD_DN%TYPE,
        P_NR_CNPJ              IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NR_CNPJ%TYPE,
        P_NM_USER_RESERVA      IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_USER_RESERVA%TYPE,
        P_DT_COMPRA            IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.DT_COMPRA%TYPE,
        P_TP_FATURAMENTO       IN     CADPD_OWN.FES_REMARKETING_ESTOQUE.TP_FATURAMENTO%TYPE,
		P_RETORNO              OUT    NUMBER
    ) IS
    BEGIN
        IF P_ID IS NULL THEN
            P_ID := CADPD_OWN.FES_REMARKETING_ESTOQUE_SEQ.NEXTVAL;
        END IF;

		P_RETORNO := P_ID;

        MERGE INTO CADPD_OWN.FES_REMARKETING_ESTOQUE t
        USING (SELECT P_ID AS ID FROM DUAL) s
        ON (t.ID = s.ID)
        WHEN MATCHED THEN
            UPDATE SET NM_PLACA = P_NM_PLACA, 
			           NM_MODELO = P_NM_MODELO, 
					   VL_FIPE = P_VL_FIPE,
                       NR_HODOMETRO = P_NR_HODOMETRO, 
					   NM_COR = P_NM_COR, 
					   NR_ANO_MODELO = P_NR_ANO_MODELO,
                       DS_LAUDO_CAUTELAR_LINK = P_DS_LAUDO_CAUTELAR, 
					   VL_VENDA = P_VL_VENDA,
                       NM_CIDADE = P_NM_CIDADE, 
					   NM_UF = P_NM_UF, 
					   FL_RESERVA = P_FL_RESERVA, 
					   CD_DN = P_CD_DN,
                       NR_CNPJ = P_NR_CNPJ,
                       NM_USER_RESERVA = P_NM_USER_RESERVA,
					   DT_COMPRA = P_DT_COMPRA,
					   TP_FATURAMENTO = P_TP_FATURAMENTO
        WHEN NOT MATCHED THEN
            INSERT (ID,
			        ID_CONFIG,
                    NR_CNPJ,
					NM_PLACA, 
					NM_MODELO, 
					VL_FIPE, 
					NR_HODOMETRO, 
					NM_COR, 
                    NR_ANO_MODELO, 
					DS_LAUDO_CAUTELAR_LINK, 
					VL_VENDA, 
					NM_CIDADE, 
					NM_UF, 
					FL_RESERVA, 
					CD_DN,
					NM_USER_RESERVA,
					DT_COMPRA,
					TP_FATURAMENTO)
            VALUES (P_ID, 
			        P_ID_CONFIG,
                    P_NR_CNPJ,
					P_NM_PLACA, 
					P_NM_MODELO, 
					P_VL_FIPE, 
					P_NR_HODOMETRO, 
					P_NM_COR, 
                    P_NR_ANO_MODELO, 
					P_DS_LAUDO_CAUTELAR, 
					P_VL_VENDA, 
					P_NM_CIDADE, 
					P_NM_UF, 
					P_FL_RESERVA, 
					P_CD_DN,
					P_NM_USER_RESERVA,
					P_DT_COMPRA,
					P_TP_FATURAMENTO);
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP MANTER REMARKETING ESTOQUE.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_REMARKETING_ESTOQUE;

    PROCEDURE SP_MANTER_REMARKETING_PARAMETROS(
        P_ID                IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS.ID%TYPE,
        P_ID_CONFIG         IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.ID_CONFIG%TYPE,
        P_NR_CNPJ           IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.NR_CNPJ%TYPE,
        P_CD_DN             IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.CD_DN%TYPE,
        P_NM_USUARIOS       IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.NM_USUARIOS%TYPE,
        P_QT_LIMITE_CARROS  IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.QT_LIMITE_CARROS%TYPE,
        P_VL_LIMITE			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS.VL_LIMITE%TYPE,
		P_RETORNO           OUT    NUMBER
    ) IS
    BEGIN
        IF P_ID IS NULL THEN
            P_ID := CADPD_OWN.FES_REMARKETING_PARAMETROS_SEQ.NEXTVAL;
        END IF;

		P_RETORNO := P_ID;

        MERGE INTO CADPD_OWN.FES_REMARKETING_PARAMETROS t
        USING (SELECT P_ID AS ID FROM DUAL) s
        ON (t.ID = s.ID)
        WHEN MATCHED THEN
            UPDATE SET NR_CNPJ = P_NR_CNPJ,
       			       CD_DN = P_CD_DN, 
					   QT_LIMITE_CARROS = P_QT_LIMITE_CARROS,
                       NM_USUARIOS = P_NM_USUARIOS,
					   VL_LIMITE = P_VL_LIMITE
        WHEN NOT MATCHED THEN
            INSERT (ID, 
			        ID_CONFIG, 
					NR_CNPJ, 
					CD_DN, 
                    NM_USUARIOS,
					QT_LIMITE_CARROS,
					VL_LIMITE)
            VALUES (P_ID, 
			        P_ID_CONFIG, 
					P_NR_CNPJ, 
					P_CD_DN, 
                    P_NM_USUARIOS,
					P_QT_LIMITE_CARROS,
					P_VL_LIMITE);
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP MANTER REMARKETING PARAMETROS.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_REMARKETING_PARAMETROS;

    PROCEDURE SP_EXPURGO_REMARKETING(
        P_TIPO_EXPURGO IN VARCHAR2 DEFAULT 'TODOS'
    ) IS
    BEGIN
        
        IF P_TIPO_EXPURGO IN ('TODOS', 'ESTOQUE') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_ESTOQUE';
        END IF;
        
        IF P_TIPO_EXPURGO IN ('TODOS', 'PARAMETROS') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_PARAMETROS';
        END IF;
        
        IF P_TIPO_EXPURGO IN ('TODOS', 'CONFIG') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_CONFIG';
        END IF;
		
		IF P_TIPO_EXPURGO IN ('TODOS', 'PARAMETROS_DN') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_PARAMETROS_DN';
        END IF;
		
		IF P_TIPO_EXPURGO IN ('TODOS', 'PARAMETROS_GRUPO_DN') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN';
        END IF;
		
		IF P_TIPO_EXPURGO IN ('TODOS', 'PARAMETROS_CATEGORIA_VEICULO') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO';
        END IF;
		
		IF P_TIPO_EXPURGO IN ('TODOS', 'PARAMETROS_CALC') THEN
           EXECUTE IMMEDIATE 'TRUNCATE TABLE CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC';
        END IF;

	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP REALIZAR EXPURGO REMARKETING.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_EXPURGO_REMARKETING;
    
    PROCEDURE SP_OBTER_REMARKETING_CONFIG_EXIBICAO( 
        P_CD_DN     IN  CADPD_OWN.FES_REMARKETING_PARAMETROS.CD_DN%TYPE,
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT FRP.ID, FRP.ID_CONFIG, FRP.NR_CNPJ, FRP.CD_DN, FRP.NM_USUARIOS, FRP.QT_LIMITE_CARROS,
                   COUNT(FRE.NM_PLACA) AS QTD_RESERVADA
              FROM CADPD_OWN.FES_REMARKETING_PARAMETROS FRP 
                   LEFT JOIN CADPD_OWN.FES_REMARKETING_ESTOQUE FRE ON FRP.CD_DN = FRE.CD_DN
             WHERE FRP.CD_DN = P_CD_DN
             GROUP BY FRP.ID, FRP.ID_CONFIG, FRP.NR_CNPJ, FRP.CD_DN, FRP.NM_USUARIOS, FRP.QT_LIMITE_CARROS;
    EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER CONFIG EXIBICAO.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_CONFIG_EXIBICAO;
    
    PROCEDURE SP_OBTER_REMARKETING_UF_CIDADE(
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT UPPER(FRE.NM_UF) AS NM_UF, UPPER(FRE.NM_CIDADE) AS NM_CIDADE
              FROM CADPD_OWN.FES_REMARKETING_ESTOQUE FRE
             GROUP BY FRE.NM_UF, FRE.NM_CIDADE
             ORDER BY FRE.NM_UF, FRE.NM_CIDADE;
    EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING UF/CIDADE.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_UF_CIDADE;
    
    PROCEDURE SP_OBTER_REMARKETING_LISTA_VEICULOS(
        P_CD_DN           IN CADPD_OWN.FES_REMARKETING_ESTOQUE.CD_DN%TYPE,
        P_NM_CIDADE       IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE DEFAULT NULL,
        P_NM_UF           IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE DEFAULT NULL,
        P_NM_MODELO          IN VARCHAR2 DEFAULT NULL,
        P_NM_PLACA           IN VARCHAR2 DEFAULT NULL,
        P_FL_STATUS       IN VARCHAR2 DEFAULT 'T',
		P_QT_ITENS_PAGINA IN OUT NUMBER,
        P_NR_PAGINA       IN OUT NUMBER,
        P_RETORNO         OUT SYS_REFCURSOR
    ) IS
        P_CNPJ_PARAMETRO VARCHAR2(20);
		V_OFFSET NUMBER;
    BEGIN

    SELECT FRP.NR_CNPJ INTO P_CNPJ_PARAMETRO
      FROM CADPD_OWN.FES_REMARKETING_PARAMETROS FRP
     WHERE FRP.CD_DN = P_CD_DN;
	 
	 IF P_QT_ITENS_PAGINA IS NULL OR P_QT_ITENS_PAGINA < 1 THEN
		P_QT_ITENS_PAGINA := 20;
	 END IF;

	 IF P_NR_PAGINA IS NULL OR P_NR_PAGINA < 1 THEN
		V_OFFSET := 1;
	 ELSE
		V_OFFSET := (P_NR_PAGINA - 1) * P_QT_ITENS_PAGINA;
	 END IF;

        OPEN P_RETORNO FOR
            SELECT FRE.ID, FRE.ID_CONFIG, 
                   NVL(FRE.NR_CNPJ,P_CNPJ_PARAMETRO) NR_CNPJ,
                   FRE.NM_PLACA, FRE.NM_MODELO, FRE.VL_FIPE, FRE.NR_HODOMETRO,
                   FRE.NM_COR, FRE.NR_ANO_MODELO, FRE.DS_LAUDO_CAUTELAR_LINK, FRE.VL_VENDA, FRE.NM_CIDADE,
                   FRE.NM_UF, FRE.FL_RESERVA, FRE.CD_DN, FRE.DT_COMPRA, FRE.TP_FATURAMENTO,
                   CASE WHEN FRE.FL_RESERVA = 'N' THEN 'D'
                        WHEN FRE.FL_RESERVA = 'S' THEN 
                                    CASE WHEN FRE.CD_DN <> P_CD_DN THEN 'O' ELSE 'R' END
                   END AS FL_STATUS, NM_USER_RESERVA,
				   
				   COUNT(*) OVER () AS QT_REGISTROS_TOTAIS,
				   CEIL(COUNT(*) OVER () / P_QT_ITENS_PAGINA) AS NR_TOTAL_PAGINAS
				   
              FROM CADPD_OWN.FES_REMARKETING_ESTOQUE FRE
             WHERE 
				(
					(P_NM_UF IS NULL
						OR TRIM(P_NM_UF) = '')
						OR UPPER( TRIM(NM_UF)) IN (
							SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_UF)), '[^,]+', 1, LEVEL)))
							FROM DUAL
							CONNECT BY REGEXP_SUBSTR(P_NM_UF, '[^,]+', 1, LEVEL) IS NOT NULL
							)
				)
                AND 
				(
					(P_NM_CIDADE IS NULL
						OR TRIM(P_NM_CIDADE) = '')
						OR UPPER(TRIM(NM_CIDADE)) IN (
							SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_CIDADE)), '[^,]+', 1, LEVEL)))
							FROM DUAL
							CONNECT BY REGEXP_SUBSTR(P_NM_CIDADE, '[^,]+', 1, LEVEL) IS NOT NULL
							)
				)
                AND 
				(
                     (P_NM_MODELO IS NULL
						OR TRIM(P_NM_MODELO) = '')
						OR UPPER(TRIM(NM_MODELO)) IN (
							SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_MODELO)), '[^,]+', 1, LEVEL)))
							FROM DUAL
							CONNECT BY REGEXP_SUBSTR(P_NM_MODELO, '[^,]+', 1, LEVEL) IS NOT NULL
							)
                )
				AND
				(
					(P_NM_PLACA IS NULL
						OR TRIM(P_NM_PLACA) = '')
						OR UPPER(TRIM(NM_PLACA)) IN (
							SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_PLACA)), '[^,]+', 1, LEVEL)))
							FROM DUAL
							CONNECT BY REGEXP_SUBSTR(P_NM_PLACA, '[^,]+', 1, LEVEL) IS NOT NULL
							)
				)
                AND ((P_FL_STATUS = 'D' AND FRE.CD_DN Is Null)
                    OR 
                    (P_FL_STATUS = 'R' AND FRE.CD_DN = P_CD_DN)
                    OR
                    P_FL_STATUS = 'T'
                   )
               ORDER BY FRE.ID
				OFFSET V_OFFSET ROWS
				FETCH NEXT P_QT_ITENS_PAGINA ROWS ONLY;
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP REALIZAR LISTA CARROS.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_LISTA_VEICULOS;
	
--ADMIN_PARCEIRO_LOCACAO (LOCALIZA)
	
    PROCEDURE SP_OBTER_ADMIN_PARCEIRO_LOCACAO
    (
        P_ID_ADMIN_PARCEIRO_LOCACAO IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.ID_ADMIN_PARCEIRO_LOCACAO%TYPE DEFAULT NULL,
        P_CD_CONCESSIONARIA         IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.CD_CONCESSIONARIA%TYPE DEFAULT NULL,
        P_FL_ESTADO_USO             IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.FL_ESTADO_USO%TYPE DEFAULT NULL,
        P_RETORNO                   OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT
                ID_ADMIN_PARCEIRO_LOCACAO,
                FL_ESTADO_USO,
                DS_USUARIO,
                DT_CRIACAO,
                DT_EXCLUSAO,
                DS_ANO_MODELO,
                CD_CONCESSIONARIA,
                NR_PLANO_1,
                NR_PLANO_2,
                NR_PLANO_3
            FROM CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO
            WHERE (ID_ADMIN_PARCEIRO_LOCACAO = P_ID_ADMIN_PARCEIRO_LOCACAO OR P_ID_ADMIN_PARCEIRO_LOCACAO IS NULL)
              AND (CD_CONCESSIONARIA         = P_CD_CONCESSIONARIA         OR P_CD_CONCESSIONARIA IS NULL)
              AND (FL_ESTADO_USO             = P_FL_ESTADO_USO             OR P_FL_ESTADO_USO IS NULL)
              AND DT_EXCLUSAO IS NULL
            ORDER BY CD_CONCESSIONARIA, FL_ESTADO_USO, DS_ANO_MODELO DESC;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR
            (
                -20001,
                'PROBLEMAS AO SP OBTER ADMIN PARCEIRO LOCACAO.'
                || CHR(13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR(13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR(13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
            );
    END SP_OBTER_ADMIN_PARCEIRO_LOCACAO;


    PROCEDURE SP_MANTER_ADMIN_PARCEIRO_LOCACAO
    (
        P_ID_ADMIN_PARCEIRO_LOCACAO IN OUT CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.ID_ADMIN_PARCEIRO_LOCACAO%TYPE,
        P_FL_ESTADO_USO             IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.FL_ESTADO_USO%TYPE,
        P_DS_USUARIO                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.DS_USUARIO%TYPE,
        P_DS_ANO_MODELO             IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.DS_ANO_MODELO%TYPE,
        P_CD_CONCESSIONARIA         IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.CD_CONCESSIONARIA%TYPE,
        P_NR_PLANO_1                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.NR_PLANO_1%TYPE,
        P_NR_PLANO_2                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.NR_PLANO_2%TYPE,
        P_NR_PLANO_3                IN     CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.NR_PLANO_3%TYPE,
        P_RETORNO                   OUT    SYS_REFCURSOR
    )
    IS
    BEGIN
        IF P_ID_ADMIN_PARCEIRO_LOCACAO IS NULL THEN
            P_ID_ADMIN_PARCEIRO_LOCACAO := CADPD_OWN.SQ_FES_ADMIN_PARCEIRO_LOC.NEXTVAL;
        END IF;

        MERGE INTO CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO T
        USING (
            SELECT P_ID_ADMIN_PARCEIRO_LOCACAO AS ID_ADMIN_PARCEIRO_LOCACAO
              FROM DUAL
        ) S
           ON (T.ID_ADMIN_PARCEIRO_LOCACAO = S.ID_ADMIN_PARCEIRO_LOCACAO)
        WHEN MATCHED THEN
            UPDATE
               SET T.FL_ESTADO_USO     = P_FL_ESTADO_USO,
                   T.DS_USUARIO        = P_DS_USUARIO,
                   T.DS_ANO_MODELO     = P_DS_ANO_MODELO,
                   T.CD_CONCESSIONARIA = P_CD_CONCESSIONARIA,
                   T.NR_PLANO_1        = P_NR_PLANO_1,
                   T.NR_PLANO_2        = P_NR_PLANO_2,
                   T.NR_PLANO_3        = P_NR_PLANO_3,
                   T.DT_EXCLUSAO       = NULL
        WHEN NOT MATCHED THEN
            INSERT
            (
                ID_ADMIN_PARCEIRO_LOCACAO,
                FL_ESTADO_USO,
                DS_USUARIO,
                DT_CRIACAO,
                DT_EXCLUSAO,
                DS_ANO_MODELO,
                CD_CONCESSIONARIA,
                NR_PLANO_1,
                NR_PLANO_2,
                NR_PLANO_3
            )
            VALUES
            (
                P_ID_ADMIN_PARCEIRO_LOCACAO,
                P_FL_ESTADO_USO,
                P_DS_USUARIO,
                SYSDATE,
                NULL,
                P_DS_ANO_MODELO,
                P_CD_CONCESSIONARIA,
                P_NR_PLANO_1,
                P_NR_PLANO_2,
                P_NR_PLANO_3
            );

        OPEN P_RETORNO FOR
            SELECT
                ID_ADMIN_PARCEIRO_LOCACAO,
                FL_ESTADO_USO,
                DS_USUARIO,
                DT_CRIACAO,
                DT_EXCLUSAO,
                DS_ANO_MODELO,
                CD_CONCESSIONARIA,
                NR_PLANO_1,
                NR_PLANO_2,
                NR_PLANO_3
            FROM CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO
            WHERE ID_ADMIN_PARCEIRO_LOCACAO = P_ID_ADMIN_PARCEIRO_LOCACAO;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR
            (
                -20001,
                'PROBLEMAS AO SP MANTER ADMIN PARCEIRO LOCACAO.'
                || CHR(13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR(13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR(13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
            );
    END SP_MANTER_ADMIN_PARCEIRO_LOCACAO;


    PROCEDURE SP_EXCLUIR_ADMIN_PARCEIRO_LOCACAO
    (
        P_CD_CONCESSIONARIA         IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.CD_CONCESSIONARIA%TYPE,
        P_DS_USUARIO                IN  CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO.DS_USUARIO%TYPE,
        P_RETORNO                   OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        UPDATE CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO
           SET DT_EXCLUSAO = SYSDATE,
               DS_USUARIO  = P_DS_USUARIO
         WHERE CD_CONCESSIONARIA = P_CD_CONCESSIONARIA
           AND DT_EXCLUSAO IS NULL;

        OPEN P_RETORNO FOR
            SELECT
                ID_ADMIN_PARCEIRO_LOCACAO,
                FL_ESTADO_USO,
                DS_USUARIO,
                DT_CRIACAO,
                DT_EXCLUSAO,
                DS_ANO_MODELO,
                CD_CONCESSIONARIA,
                NR_PLANO_1,
                NR_PLANO_2,
                NR_PLANO_3
            FROM CADPD_OWN.FES_ADMIN_PARCEIRO_LOCACAO
            WHERE CD_CONCESSIONARIA = P_CD_CONCESSIONARIA;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR
            (
                -20001,
                'PROBLEMAS AO SP EXCLUIR ADMIN PARCEIRO LOCACAO.'
                || CHR(13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR(13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR(13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
            );
    END SP_EXCLUIR_ADMIN_PARCEIRO_LOCACAO;	
	
	PROCEDURE SP_OBTER_MODELO(
    P_NM_UF     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
    P_NM_CIDADE IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
    P_NM_PLACA  IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,
    P_RETORNO    OUT SYS_REFCURSOR
	) 
	IS
	BEGIN
    OPEN P_RETORNO FOR
        SELECT
            TRIM(NM_MODELO) AS NM_MODELO
        FROM
            CADPD_OWN.FES_REMARKETING_ESTOQUE
        WHERE
            (
				(P_NM_UF IS NULL
					OR TRIM(P_NM_UF) = '')
					OR UPPER( TRIM(NM_UF)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_UF)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_UF, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND 
			(
				(P_NM_CIDADE IS NULL
					OR TRIM(P_NM_CIDADE) = '')
					OR UPPER(TRIM(NM_CIDADE)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_CIDADE)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_CIDADE, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)                
			AND
			(
				(P_NM_PLACA IS NULL
					OR TRIM(P_NM_PLACA) = '')
					OR UPPER(TRIM(NM_PLACA)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_PLACA)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_PLACA, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
        GROUP BY
            TRIM(NM_MODELO)
        ORDER BY
            TRIM(NM_MODELO);
			
		EXCEPTION
			  WHEN OTHERS THEN
						 RAISE_APPLICATION_ERROR (-20001,
						 'PROBLEMAS NA SP OBTER MODELOS.'
						 || CHR (13)
						 || 'SQLERRM: '
						 || SQLERRM
						 || CHR (13)
						 || 'ERROR_STACK: '
						 || DBMS_UTILITY.FORMAT_ERROR_STACK
						 || CHR (13)
						 || 'ERROR_BACKTRACE: '
						 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_OBTER_MODELO;
	
	PROCEDURE SP_OBTER_PLACA(
    P_NM_UF     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
    P_NM_CIDADE IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
    P_NM_MODELO  IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
    P_RETORNO    OUT SYS_REFCURSOR
	) 
	IS
	BEGIN
    OPEN P_RETORNO FOR
        SELECT
            TRIM(NM_PLACA) AS NM_PLACA
        FROM
            CADPD_OWN.FES_REMARKETING_ESTOQUE
        WHERE
            (
				(P_NM_UF IS NULL
					OR TRIM(P_NM_UF) = '')
					OR UPPER( TRIM(NM_UF)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_UF)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_UF, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND 
			(
				(P_NM_CIDADE IS NULL
					OR TRIM(P_NM_CIDADE) = '')
					OR UPPER(TRIM(NM_CIDADE)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_CIDADE)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_CIDADE, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND 
			(
				 (P_NM_MODELO IS NULL
					OR TRIM(P_NM_MODELO) = '')
					OR UPPER(TRIM(NM_MODELO)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_MODELO)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_MODELO, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)			
        GROUP BY
            TRIM(NM_PLACA)
        ORDER BY
            TRIM(NM_PLACA);
			
		EXCEPTION
			  WHEN OTHERS THEN
						 RAISE_APPLICATION_ERROR (-20001,
						 'PROBLEMAS NA SP OBTER PLACAS.'
						 || CHR (13)
						 || 'SQLERRM: '
						 || SQLERRM
						 || CHR (13)
						 || 'ERROR_STACK: '
						 || DBMS_UTILITY.FORMAT_ERROR_STACK
						 || CHR (13)
						 || 'ERROR_BACKTRACE: '
						 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_OBTER_PLACA;
	
	PROCEDURE SP_OBTER_UF(
		P_NM_MODELO     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
		P_NM_PLACA      IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,
		P_NM_CIDADE     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_CIDADE%TYPE,
		P_RETORNO    OUT SYS_REFCURSOR
	) 
	IS
	BEGIN
    OPEN P_RETORNO FOR
        SELECT
            TRIM(NM_UF) AS NM_UF
        FROM
            CADPD_OWN.FES_REMARKETING_ESTOQUE
        WHERE
			(
				(P_NM_CIDADE IS NULL
					OR TRIM(P_NM_CIDADE) = '')
					OR UPPER(TRIM(NM_CIDADE)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_CIDADE)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_CIDADE, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND 
			(
				 (P_NM_MODELO IS NULL
					OR TRIM(P_NM_MODELO) = '')
					OR UPPER(TRIM(NM_MODELO)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_MODELO)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_MODELO, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND
			(
				(P_NM_PLACA IS NULL
					OR TRIM(P_NM_PLACA) = '')
					OR UPPER(TRIM(NM_PLACA)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_PLACA)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_PLACA, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
        GROUP BY
            TRIM(NM_UF)
        ORDER BY
            TRIM(NM_UF);
			
		EXCEPTION
			  WHEN OTHERS THEN
						 RAISE_APPLICATION_ERROR (-20001,
						 'PROBLEMAS NA SP OBTER UFS.'
						 || CHR (13)
						 || 'SQLERRM: '
						 || SQLERRM
						 || CHR (13)
						 || 'ERROR_STACK: '
						 || DBMS_UTILITY.FORMAT_ERROR_STACK
						 || CHR (13)
						 || 'ERROR_BACKTRACE: '
						 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_OBTER_UF;
		
	PROCEDURE SP_OBTER_CIDADE(
		P_NM_UF         IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_UF%TYPE,
        P_NM_MODELO     IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_MODELO%TYPE,
		P_NM_PLACA      IN CADPD_OWN.FES_REMARKETING_ESTOQUE.NM_PLACA%TYPE,		
		P_RETORNO    OUT SYS_REFCURSOR
	) 
	IS
	BEGIN
    OPEN P_RETORNO FOR
        SELECT
            TRIM(NM_CIDADE) AS NM_CIDADE
        FROM
            CADPD_OWN.FES_REMARKETING_ESTOQUE
        WHERE
            (
				(P_NM_UF IS NULL
					OR TRIM(P_NM_UF) = '')
					OR UPPER( TRIM(NM_UF)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_UF)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_UF, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND 			
			(
				 (P_NM_MODELO IS NULL
					OR TRIM(P_NM_MODELO) = '')
					OR UPPER(TRIM(NM_MODELO)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_MODELO)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_MODELO, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
			AND
			(
				(P_NM_PLACA IS NULL
					OR TRIM(P_NM_PLACA) = '')
					OR UPPER(TRIM(NM_PLACA)) IN (
						SELECT UPPER(TRIM(REGEXP_SUBSTR(UPPER(TRIM(P_NM_PLACA)), '[^,]+', 1, LEVEL)))
						FROM DUAL
						CONNECT BY REGEXP_SUBSTR(P_NM_PLACA, '[^,]+', 1, LEVEL) IS NOT NULL
						)
			)
        GROUP BY
            TRIM(NM_CIDADE)
        ORDER BY
            TRIM(NM_CIDADE);
			
		EXCEPTION
			  WHEN OTHERS THEN
						 RAISE_APPLICATION_ERROR (-20001,
						 'PROBLEMAS NA SP OBTER CIDADE.'
						 || CHR (13)
						 || 'SQLERRM: '
						 || SQLERRM
						 || CHR (13)
						 || 'ERROR_STACK: '
						 || DBMS_UTILITY.FORMAT_ERROR_STACK
						 || CHR (13)
						 || 'ERROR_BACKTRACE: '
						 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	END SP_OBTER_CIDADE;
	
	--NOVOS PARAMETROS DE REMARKETING (DN - GRUPODN - CATEG_VEIC - CALC)
	
	PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_DN(
        P_ID						IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.ID%TYPE,
		P_CD_DN             		IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.CD_DN%TYPE,
		P_NR_CNPJ           	    IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.NR_CNPJ%TYPE,    
		P_NM_USUARIOS_COMPRA        IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.NM_USUARIOS_COMPRA%TYPE,
		P_NM_USUARIOS_RELATORIO     IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.NM_USUARIOS_RELATORIO%TYPE,
		P_RETORNO           		OUT    NUMBER
    ) IS
    BEGIN
        IF P_ID IS NULL OR P_ID = 0 THEN
            P_ID := CADPD_OWN.FES_REMARKETING_PARAMETROS_DN_SEQ.NEXTVAL;
        END IF;

		P_RETORNO := P_ID;

        MERGE INTO CADPD_OWN.FES_REMARKETING_PARAMETROS_DN t
        USING (SELECT P_ID AS ID FROM DUAL) s
        ON (t.ID = s.ID)
        WHEN MATCHED THEN
            UPDATE SET 	CD_DN = P_CD_DN,
						NR_CNPJ = P_NR_CNPJ,       			        
						NM_USUARIOS_COMPRA = P_NM_USUARIOS_COMPRA,
						NM_USUARIOS_RELATORIO = P_NM_USUARIOS_RELATORIO						
        WHEN NOT MATCHED THEN
            INSERT (ID,
					CD_DN,
					NR_CNPJ,					 
                    NM_USUARIOS_COMPRA,					
					NM_USUARIOS_RELATORIO)
            VALUES (P_ID, 
			        P_CD_DN, 
					P_NR_CNPJ,
					P_NM_USUARIOS_COMPRA,					
					P_NM_USUARIOS_RELATORIO);
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP MANTER REMARKETING PARAMETROS DN.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_REMARKETING_PARAMETROS_DN;
	
PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_GRUPO_DN(
        P_ID                   			IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.ID%TYPE,                   
		P_NM_GRUPO             			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.NM_GRUPO%TYPE,             	
		P_NM_CATEGORIA         			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.NM_CATEGORIA%TYPE,         	
		P_DS_CATEGORIA         			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.DS_CATEGORIA%TYPE,         	
		P_CD_DN                			IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.CD_DN%TYPE,                	
		P_QT_LIMITE_TP_FATURAMENTO		IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.QT_LIMITE_TP_FATURAMENTO%TYPE,
		P_VL_LIMITE_TP_FATURAMENTO 		IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.VL_LIMITE_TP_FATURAMENTO%TYPE,
		P_TP_FATURAMENTO                IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN.TP_FATURAMENTO%TYPE,          
		P_RETORNO			 			OUT    NUMBER
    ) IS
    BEGIN
        IF P_ID IS NULL OR P_ID = 0 THEN
            P_ID := CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN_SEQ.NEXTVAL;
        END IF;

		P_RETORNO := P_ID;

        MERGE INTO CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN t
        USING (SELECT P_ID AS ID FROM DUAL) s
        ON (t.ID = s.ID)
        WHEN MATCHED THEN
            UPDATE SET 	NM_GRUPO = P_NM_GRUPO,
						NM_CATEGORIA = P_NM_CATEGORIA,
						DS_CATEGORIA = P_DS_CATEGORIA,
						CD_DN = P_CD_DN,
						QT_LIMITE_TP_FATURAMENTO = P_QT_LIMITE_TP_FATURAMENTO,
						VL_LIMITE_TP_FATURAMENTO = P_VL_LIMITE_TP_FATURAMENTO,
						TP_FATURAMENTO = P_TP_FATURAMENTO						
        WHEN NOT MATCHED THEN
            INSERT (ID,
					NM_GRUPO,             	
					NM_CATEGORIA,         	
					DS_CATEGORIA,         	
					CD_DN,                	
					QT_LIMITE_TP_FATURAMENTO,
					VL_LIMITE_TP_FATURAMENTO,
					TP_FATURAMENTO)
            VALUES (P_ID, 
			        P_NM_GRUPO,      
					P_NM_CATEGORIA,
					P_DS_CATEGORIA,
					P_CD_DN,
					P_QT_LIMITE_TP_FATURAMENTO,
					P_VL_LIMITE_TP_FATURAMENTO,
					P_TP_FATURAMENTO);
	EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP MANTER REMARKETING PARAMETROS GRUPO DN.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_REMARKETING_PARAMETROS_GRUPO_DN;	

PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_CATEGORIA_VEICULO(
        P_ID                      IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO.ID%TYPE,
        P_NM_CATEGORIA            IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO.NM_CATEGORIA%TYPE,
        P_DS_CATEGORIA            IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO.DS_CATEGORIA%TYPE,
        P_RETORNO                 OUT    NUMBER
    ) IS
    BEGIN
        IF P_ID IS NULL OR P_ID = 0 THEN
            P_ID := CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO_SEQ.NEXTVAL;
        END IF;

        P_RETORNO := P_ID;

        MERGE INTO CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO t
        USING (SELECT P_ID AS ID FROM DUAL) s
        ON (t.ID = s.ID)
        WHEN MATCHED THEN
            UPDATE SET  NM_CATEGORIA = P_NM_CATEGORIA,
                        DS_CATEGORIA = P_DS_CATEGORIA                        
        WHEN NOT MATCHED THEN
            INSERT (ID,
                    NM_CATEGORIA,
                    DS_CATEGORIA)
            VALUES (P_ID, 
                    P_NM_CATEGORIA, 
                    P_DS_CATEGORIA);

    EXCEPTION
      WHEN OTHERS THEN
                 RAISE_APPLICATION_ERROR (-20001,
                 'PROBLEMAS AO SP MANTER REMARKETING CATEGORIA VEICULO.'
                 || CHR (13)
                 || 'SQLERRM: '
                 || SQLERRM
                 || CHR (13)
                 || 'ERROR_STACK: '
                 || DBMS_UTILITY.FORMAT_ERROR_STACK
                 || CHR (13)
                 || 'ERROR_BACKTRACE: '
                 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_MANTER_REMARKETING_PARAMETROS_CATEGORIA_VEICULO;
	
PROCEDURE SP_MANTER_REMARKETING_PARAMETROS_CALC(
        P_ID                          IN OUT CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.ID%TYPE,
        P_NM_GRUPO_DN                 IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.NM_GRUPO_DN%TYPE,
        P_DS_GRUPO_DN                 IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.DS_GRUPO_DN%TYPE,
        P_QT_LIMITE_DESCONTO          IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.QT_LIMITE_DESCONTO%TYPE,
        P_VL_LIMITE_DESCONTO          IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.VL_LIMITE_DESCONTO%TYPE,
        P_QT_DESCONTO_VEICULO_B       IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.QT_DESCONTO_VEICULO_B%TYPE,
        P_QT_DESCONTO_VEICULO_C       IN     CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC.QT_DESCONTO_VEICULO_C%TYPE,
        P_RETORNO                     OUT    NUMBER
    ) IS
    BEGIN
        IF P_ID IS NULL OR P_ID = 0 THEN
            P_ID := CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC_SEQ.NEXTVAL;
        END IF;

        P_RETORNO := P_ID;

        MERGE INTO CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC t
        USING (SELECT P_ID AS ID FROM DUAL) s
        ON (t.ID = s.ID)
        WHEN MATCHED THEN
            UPDATE SET  NM_GRUPO_DN = P_NM_GRUPO_DN,
                        DS_GRUPO_DN = P_DS_GRUPO_DN,
                        QT_LIMITE_DESCONTO = P_QT_LIMITE_DESCONTO,
                        VL_LIMITE_DESCONTO = P_VL_LIMITE_DESCONTO,
                        QT_DESCONTO_VEICULO_B = P_QT_DESCONTO_VEICULO_B,
                        QT_DESCONTO_VEICULO_C = P_QT_DESCONTO_VEICULO_C
        WHEN NOT MATCHED THEN
            INSERT (ID,
                    NM_GRUPO_DN,
                    DS_GRUPO_DN,
                    QT_LIMITE_DESCONTO,
                    VL_LIMITE_DESCONTO,
                    QT_DESCONTO_VEICULO_B,
                    QT_DESCONTO_VEICULO_C)
            VALUES (P_ID,
                    P_NM_GRUPO_DN,
                    P_DS_GRUPO_DN,
                    P_QT_LIMITE_DESCONTO,
                    P_VL_LIMITE_DESCONTO,
                    P_QT_DESCONTO_VEICULO_B,
                    P_QT_DESCONTO_VEICULO_C);

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR (-20001,
                'PROBLEMAS AO SP MANTER REMARKETING PARAMETROS CALC.'
                || CHR (13)
                || 'SQLERRM: '
                || SQLERRM
                || CHR (13)
                || 'ERROR_STACK: '
                || DBMS_UTILITY.FORMAT_ERROR_STACK
                || CHR (13)
                || 'ERROR_BACKTRACE: '
                || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END SP_MANTER_REMARKETING_PARAMETROS_CALC;

PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_DN(
		P_CD_DN     IN  CADPD_OWN.FES_REMARKETING_PARAMETROS_DN.CD_DN%TYPE,
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT *FROM CADPD_OWN.FES_REMARKETING_PARAMETROS_DN
			WHERE CD_DN = P_CD_DN;
    EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING PARAMETROS DN.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_PARAMETROS_DN;
	
PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_GRUPO_DN(		
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT *FROM CADPD_OWN.FES_REMARKETING_PARAMETROS_GRUPO_DN;
    EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING PARAMETROS GRUPO DN.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_PARAMETROS_GRUPO_DN;
	
PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_CATEGORIA_VEICULO(		
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT *FROM CADPD_OWN.FES_REMARKETING_PARAMETROS_CATEGORIA_VEICULO;
    EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING PARAMETROS CATEGORIA VEICULO.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_PARAMETROS_CATEGORIA_VEICULO;
	
PROCEDURE SP_OBTER_REMARKETING_PARAMETROS_CALC(		
        P_RETORNO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RETORNO FOR
            SELECT *FROM CADPD_OWN.FES_REMARKETING_PARAMETROS_CALC;
    EXCEPTION
	  WHEN OTHERS THEN
				 RAISE_APPLICATION_ERROR (-20001,
				 'PROBLEMAS AO SP OBTER REMARKETING PARAMETROS CATEGORIA VEICULO.'
				 || CHR (13)
				 || 'SQLERRM: '
				 || SQLERRM
				 || CHR (13)
				 || 'ERROR_STACK: '
				 || DBMS_UTILITY.FORMAT_ERROR_STACK
				 || CHR (13)
				 || 'ERROR_BACKTRACE: '
				 || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END SP_OBTER_REMARKETING_PARAMETROS_CALC;
	
END PG_FRONT_END_SYSTEM;
/
GRANT EXECUTE ON CADPD_OWN.PG_FRONT_END_SYSTEM TO CADPD_OWN;